# Codecov configuration
coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 55%
        threshold: 5%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "examples/"
  - "**/__init__.py"